inc/PROcreate.h

guanqun found bug in getuniverseweights

---

inc/PROconfig.h
src/PROconfig.cxx
src/PROtocall.cxx

allow channels to have zero true bin

Add flexibility in channel true bins

---

inc/PROconfig.h
inc/PROtocall.h
src/PROconfig.cxx
src/PROtocall.cxx

Add function to find subchannel index, provided global bin index

pull request for subchannel index finding

---

bin/PROfit_CAFAna.cxx
inc/PROspec.h
inc/PROsyst.h
src/PROspec.cxx
src/PROsyst.cxx
xml/PROxml_CAFAna.xml

Add a Poisson variation function to PROspec. Do we want other variation functions?
Add a few more variants of the GetSplineShiftedSpectrum functions which will work with syst number instead of name.
Update PROfit_CAFAna to fit a random throw as an example.

Functions for random throws

---

bin/PROfc.cxx
src/PROchi.cxx

Update PROfc to work after changes made last week during the workshop.
Add a few plots.
Still using 10 random seeds instead of latin hypercube, holding off on that until we have an actual Fitter class we can use instead.

Update PROfc to work after workshop changes

---

bin/PROsurf.cxx
inc/PROsurf.h
src/PROcreate.cxx
src/PROsurf.cxx
xml/ICARUS_run2_numudis.xml
xml/PROxml_nosyst.xml

Replace FillSurfaceSimple with FillSurfaceStat in PROsurf
Add two new xml files
1. ICARUS_run2_numudis.xml - New "standard" xml for ICARUS run 2 analysis
2. PROxml_nosyst.xml - same as above, but without systematics. Not meant as a "standard" xml, but more as an example.

Stat Surface and ICARUS xml

---

bin/PROsurf.cxx
inc/PROcess.h
inc/PROsyst.h
src/PROcess.cxx
src/PROsyst.cxx

Add some new flags to PROsurf, and functions to PROcess and PROsyst to facilitate that functionality

More PROsurf Options

---

src/PROsurf.cxx

Allow for making surfaces with only a covariance and no splines

---

src/PROcreate.cxx

New branches added to sBruce tress include the knob values for each "spline" universe. This means we no longer have to assume it's -3, -2, -1, 0, 1, 2, 3.
This enables on/off systematics such as DecayAngMEC, and should make it easier to use the SPINE files Justin has produced (though those still need these new branches to really work).

Add ability to read _sigma branches from sBruce trees

---

bin/PROplot.cxx
inc/PROconfig.h
inc/PROspec.h
src/PROcess.cxx
src/PROconfig.cxx
src/PROspec.cxx
xml/ICARUS_run2_numudis.xml

~~Draft PR for now. Will update to PR when I get feedback on what we want to plot and when I've thought more about the interface.~~
Plot a bunch of useful things and save to pdf or root file.

Update PROplot to plot some useful things 

---

bin/PROfit.cxx
bin/PROmock.cxx
inc/PROCNP.h
inc/PROchi.h
inc/PROmetric.h
inc/PROsurf.h
src/PROsurf.cxx

PROfile now takes the PROmetric as well to manage some bounds, as well as nthread for multthreading
PROfile(myConf, myprop, systs, osc, data, chi,filename, true, nthread);

PROfile made a class for threading support

---

src/PROconfig.cxx
src/PROcreate.cxx
xml/ICARUS_run2_numudis.xml

Some seg faults when testing multiple branches in an MCFile
Also updated the ICARUS run 2 xml to use multiple branches in a single MCFile

Bugfix for multibranch mcfiles

---

inc/PROconfig.h
src/PROconfig.cxx
src/PROsurf.cxx
xml/ICARUS_run2_numudis.xml

This also include fix from #155 since I needed it for testing, so that should be merged first.

Add plotname attribute to systematics

---

bin/PROfit.cxx

Use new syst plot names in PROfit

---

bin/PROfc.cxx
bin/PROfit.cxx
inc/PROlog.h

Log to a file instead of cout

---

bin/PROfit.cxx
inc/PROcreate.h
src/PROcreate.cxx

added a flag for using xrootd. XrootD is on by default,flag turns off

---

bin/PROfit.cxx
inc/PROsurf.h
src/PROsurf.cxx

Also adds new master histogram plotting function which is currently only used for PROfile. We can update the other plots to use it in the future.

Plot PROfile result

---

bin/PROfit.cxx
inc/PROsyst.h
src/PROsurf.cxx
src/PROsyst.cxx

~Draft until I get more feadback~
Good to go I think, but 90% bands are a bit weird. Still need to test on the grid.

Brazil Band

---

bin/PROfit.cxx
inc/PROMCMC.h
inc/PROsyst.h
src/PROsurf.cxx
src/PROsyst.cxx

Add MCMC and use for post-fit error bands

---

bin/PROfit.cxx
inc/PROMCMC.h
inc/PROcess.h
src/PROcess.cxx

This likely have conflicts in at least one place with #191

Use global rng seed in more places

---

bin/PROfit.cxx

I merged #191 into this to get some changes to the plotting function I made there, so that should be merged first.

area normalized plotting

---

bin/PROfit.cxx
inc/PROCNP.h
inc/PROMCMC.h
inc/PROchi.h
inc/PROmetric.h
inc/PROpoisson.h

And adaptive MCMC which is not turned on by default.

MCMC from the commandline and pre-fit MCMC

---

bin/PROfit.cxx
xml/ICARUS_run2_numudis_Apr11_2025.xml

Add data/MC and data/Best Fit ratio plots
Remove null variation from nominal list of systematics

Ratio Plots

---

bin/PROfit.cxx
inc/PROfitter.h

And make number of iterations in PROfitter finite to avoid infinite loops

Use LDLT for FC throws

---

bin/PROfit.cxx
inc/PROconfig.h
inc/PROspec.h
src/PROconfig.cxx
src/PROcreate.cxx
src/PROfc.cxx
src/PROspec.cxx

Flag for poisson variations to fake data
Fake data from systematics excluded from the fits
Override knob values for splines from the xml

More Fake Data Features
